### ISSUE TITLE
vni-manager.js should create initial output and error states with undefined LMs

### ISSUE THREAD

**Issue by dbooth-boston** [rdf-pipeline/noflo-rdf-pipeline#32]
On lines 89 and 90 at https://github.com/rdf-pipeline/noflo-rdf-components/blob/0e70efa1cab499fbbaeb47d42cbe10fb9f39d022/src/vni-manager.js#L89
instead of

<pre>
                      errorState: stateFactory( vnid, '' ), 
                      outputState: stateFactory( vnid, '' ),
</pre>

it should be

<pre>
                      errorState: stateFactory( vnid, '', undefined ), 
                      outputState: stateFactory( vnid, '', undefined ),
</pre>

after updating create-state.js as described at issue 31:
https://github.com/rdf-pipeline/noflo-rdf-pipeline/issues/31

**Comment by glenna-m** [comment]
That is problematic because most of our current code base expects that an undefined LM means we should generate a new LM automatically in the state factory.   How do we handle the default and most common case then?  The only way I could enforce an undefined LM on this without breaking the default LM use case would be to set it after the factory call.   Thoughts?

**Comment by glenna-m** [comment]
Sure looks to me like it is already doing this.  The line numbers on this issue are wrong since the code has changed over time.  However, this is how the output state and error state are currently created: 

```
99 if ( _.isUndefined( this.vnis[vnid] )  ) {
100                   // have no vni so create one with empty error & output state
101                   var componentName = _.isUndefined(this.componentName) ? '' : this.componentName;
102                   this.vnis[vnid] = {
103                       errorState: stateFactory( vnid,
104                                                 undefined,  // no data yet
105                                                 undefined,  // no lm yet
106                                                 undefined,  // not an error
107                                                 undefined,  // not stale
108                                                 undefined,  // no groupLm
109                                                 componentName ),
110                       outputState: stateFactory( vnid,
111                                                  undefined,  // no data yet
112                                                  undefined,  // no lm yet
113                                                  undefined,  // not an error
114                                                  undefined,  // not stale
115                                                  undefined,  // no groupLm
116                                                  componentName )
117                   };
118 
119                   // TODO: Add parentVni setting here
120               }

```

Asking issue submitter to review this.

**Comment by dbooth-boston** [comment]
Agreed.  I'll close this issue.  Thanks
