### ISSUE TITLE
haveAllInputs should return false if any state.error is set

### ISSUE THREAD

**Issue by dbooth-boston** [rdf-pipeline/noflo-rdf-pipeline#34]
In framework-ondata.js haveAllInputs currently only checks for undefined states:

<pre>
 +        return ( _.isUndefined( states ) || 
+               ( _.isArray( states ) &&  _.some( states, _.isUndefined )));
</pre>

But now that we have added the state.error property, it should also check that state.error is not set, because an updater should not run if one of its inputs has state.error set.

**Comment by glenna-m** [comment]
This issue as already been addressed, but not where documented.  The shouldRunUpdater function reads: 

function shouldRunUpdater(vni, isStale) {
    // TODO: May add different policies in the future.
    return (!isStale) && haveAllInputs(vni) && dataIsGood(vni);
}

The dataIsGood API is the one that is actually checking that no input has the error flag set: 

function dataIsGood(vni) {
    var attachedInPorts = attachedInputPorts(vni.nodeInstance);
    var lastOutput = vni.outputState();

```
return _.some(attachedInPorts, function(port) {
    var states = vni.inputStates(port.name);
    return ! (haveInputErrors( states) ||  inputDataUndef(states, lastOutput));
});
```

}

With its call to the haveInputErrors API:
function haveInputErrors(states) {

```
if (_.isArray(states)) {
    return _.reduce(states, function(result, state) {
        return result || state.error;
    }, false);
} else if (_.isObject(states)) {
    return (states.error === true);
}

return false;
```

}

I believe this issue can be closed with no change now.

**Comment by dbooth-boston** [comment]
ok, sounds good.
