### ISSUE TITLE
Need a way to generate and pass graph URIs based on IDs in data

### ISSUE THREAD

**Issue by dbooth-boston** [rdf-pipeline/noflo-rdf-pipeline#43]
For example, this generated turtle:

```
[] a fhir:MedicationDispense;
   fhir:MedicationDispense.id [ fhir:value "urn:local:fhir:MedicationDispense:52-40863" ];
```

should be in a graph called something like urn:local:fhir:MedicationDispense:52-40863 and should be:

```
<urn:local:fhir:MedicationDispense:52-40863> a fhir:MedicationDispense;
   fhir:MedicationDispense.id [ fhir:value "urn:local:fhir:MedicationDispense:52-40863" ];
```

**Comment by glenna-m** [comment]
I have this one. Mike and Eric, I don't think you need to do anything on this.

**Comment by dbooth-boston** [comment]
Glenna is doing a temporary fix for this, but I want to keep this issue open until I figure out a more proper way to handle it in the pipeline architecture.

**Comment by dbooth-boston** [comment]
We addressed this by adding metadata to the state.
